name: web-react-app
description: Stack react for micro frontend
types:
  - app-template
inputs:
  - label: "Project name(must not have spaces and be lowercase)"
    type: text
    name: "project_name"
    global: true
    default: "stackfront_web"
  - label: "Add routing to app?"
    type: bool
    name: "add_routing"
    default: true
