name: web-react-app
description: Stack react for micro frontend
types:
  - app-template
inputs:
  - label: "Project name(must not have spaces and be lowercase)"
    type: text
    name: "application_name"
    default: "stackfront_web"
  - label: "Is Widget?"
    type: bool
    name: "is_widget"
    default: false
